[build]
  command = "npm run build"
  base = "/"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "index.html"
  base = "/"
  
[[plugins]]
  package = "netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
